app:
    controller:
        exception:
            message1: Id and Password Empty
            message2: Id and Password not found
            message3: Id and Password invalid
    jwttoken:
        message: Login Successful
    service:
        message1: User Already Exists
        message2: Invalid Id and Password
    validationConfirmationMessage: You have been validated!
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        server-url:
            defaultZone: http://localhost:8761/eureka
jwt:
    secret: secret
server:
    port: 8089
spring:
    application:
        name: user-management-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/registered_users?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
